### ISSUE TITLE
Error when the cache is updated

### ISSUE THREAD

**Issue by twsh** [msprev/unite-bibtex#4]
If there is no cache or the cache is stale I get the following error when I do `Unite bibtex`. If I do it a second time it's fine. So it looks like the first time the cache is actually created/updated and then on the second attempt Unite is able to use it.

```
[unite.vim] function <SNR>22_call_unite..unite#start..unite#start#standard..unit
e#candidates#_recache..<SNR>46_recache_candidates_loop..<SNR>46_get_source_candi
dates..7, line 25
[unite.vim] Vim(python):No handlers could be found for logger "bibtexparser.bpar
ser"
[unite.vim] Error occurred in gather_candidates!
[unite.vim] Source name is bibtex
```

**Comment by msprev** [comment]
Thanks for reporting this. The exception is being thrown by the bibtex parser. Once the cache has been generated, the parser is no longer called.

There is a chance that the error is because your bibtex file isn't 100% clean (bibtex is a nightmare to parse). Could you try with the minimal bibtex file below and see if it generates the error?

```
@book{Test01,
    Address = {Somewhere},
    Author = {Author, A.},
    Publisher = {Publisher},
    Title = {Title},
    Year = {2010},
    }
```

**Comment by msprev** [comment]
I've also just pushed an update that should catch the warnings and errors from bibtexparser inside vim without the entire process failing. Try deleting the cache, run `Unite bibtex`, and then type `:messages` in vim to see any warnings or errors from the bibtex parser.

**Comment by twsh** [comment]
Thanks. That works now with my file output by JabRef and your test.
