### ISSUE TITLE
Sorry, the command is not available in this version

### ISSUE THREAD

**Issue by twsh** [msprev/unite-bibtex#6]
I recently upgraded to Ubuntu 16.04. I'm now getting a problem with unite-bibtex. (I have the latest version installed via Vundle). I have Vim 7.4.1689 which is the latest version in the Ubuntu repository. This is the error:

```
[unite.vim] function <SNR>22_call_unite[33]..unite#start[1]..unite#start#standar
d[50]..unite#candidates#_recache[74]..<SNR>98_recache_candidates_loop[42]..<SNR>
98_get_source_candidates[40]..103, line 25
[unite.vim] Vim(python):E319: Sorry, the command is not available in this versio
n:     python import unitebibtex; unitebibtex.vim_bridge_gather_candidates()
[unite.vim] Error occurred in gather_candidates!
[unite.vim] Source name is bibtex
```

I have bibtexparser installed. And Unite itself seems to be working fine. Have you seen this kind of error before? Do you know where I should start looking?

**Comment by msprev** [comment]
That is strange. Perhaps you vim build does not include python? Can you try `:python print(2+2)` in vim and see if it works?

**Comment by twsh** [comment]
That put me in the right direction, thanks: Vim in Ubuntu 16.04 uses python3: https://wiki.ubuntu.com/XenialXerus/ReleaseNotes#VIM_defaults_to_python3

**Comment by msprev** [comment]
Thanks for this. I haven't tested it with vim built with python3. Does it work correctly once you install bibtexparser for python3?

**Comment by twsh** [comment]
No, I was getting a different error message then.

It looks like some of the python code doesn't work with python3. I made the changes suggested by 2to3 in a local version, but that didn't fix it. I think one issue might be the use of relative imports. I might look at it more when I have time.

I've switched to a version of Vim built with python 2 for the moment.

**Comment by msprev** [comment]
Thanks, that is good to know. Relative imports have changed from python 2 to 3, so that must be it.

**Comment by twsh** [comment]
Here's the error I get now:

```
[unite.vim] function <SNR>22_call_unite[33]..unite#start[1]..unite#start#standar
d[50]..unite#candidates#_recache[74]..<SNR>79_recache_candidates_loop[42]..<SNR>
79_get_source_candidates[40]..103, line 25
[unite.vim] Vim(python3):Traceback (most recent call last):
[unite.vim] Error occurred in gather_candidates!
[unite.vim] Source name is bibtex
```

One thing I noticed is that when I lint unitebibtex.py I get a series of 'no-member' errors for the vim package. I have python-vim through pip3 though, and I can do `import vim` in a python3 shell.

**Comment by msprev** [comment]
It won't work for python3. I haven't tested it with vim+python3 as I wasn't aware of that being widely used. I'd need to so some rewriting to get it working for python3. Any PRs on this are welcome!

The linting errors are because your linter thinks that the vim package does not exist in your distribution to import.

**Comment by twsh** [comment]
I thought I would have a go. But I'm now stuck. Here's what I did:
- Went through all the .py files and changed them to python3
- Changed the command in bibtex.vim to `python3`
- Made all the import paths either absolute or explicitly relative
- Change the hashbang in bibwatch.py to `python3`

Now all the files lint fine. And I can do `:python3 import unitebibtex` without getting an error. And I can do `python3 vim.command('echo "Hello World!"')` and get the right output (I read that this is a test for the vim package being properly installed). But I still get the error.

**Comment by msprev** [comment]
It's non-trivial to change because the rules on relative imports changed from python 2 to python 3. The plugin needs some significant refactoring here to run under python 3. 

If you want to work on it, forget on using vim as an interface (a pain to debug python plugins!). Instead, use the python3 repl from the command line. Go into `core` folder and focus on the modules there. `import gather` and step through the relevant operations by hand. You can poke around in the data that gets sent to/from vim by the plugin. I designed the core of the plugin to be independent from vim so it could be debugged outside vim. `unitebibtex.py` is the very minimal bridge to vim.
